version: "3.9"
   
services:
  db:
    image: postgres
    env_file:
      - dev.env
    ports:
      - "5432:5432"
  backend:
    build: .
    env_file:
      - dev.env
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db