# Generated by Django 4.0.2 on 2022-03-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_name_appuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_account_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.EmailField(max_length=256, unique=True),
        ),
    ]
