# Generated by Django 4.0.2 on 2022-03-10 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_appuser_is_account_active_alter_appuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='is_account_active',
        ),
    ]
