# Generated by Django 4.0.2 on 2022-04-08 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_appuser_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='gender',
            new_name='avatar',
        ),
    ]
